/**
 * Generated by `npm run generate:api` (openapi-typescript) from the
 * backend's published OpenAPI spec (0.0.8 — `mvn -Popenapi verify
 * -DskipTests` in backend/, which writes backend/target/openapi.yaml).
 *
 * This checked-in copy is a placeholder until that generation is run
 * against a real backend build: no backend endpoints are consumed by any
 * screen yet (Epic F0.0 is scaffold-only), so `paths` is empty. Do not
 * hand-edit — regenerate instead. See src/lib/api/client.ts and
 * scripts/generate-api.mjs.
 */

export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type operations = Record<string, never>;
