-- IAM-9 / ADM-1: marks an account whose current password was generated by
-- the system (bootstrap platform admin, brand-admin/tenant-admin
-- provisioning) rather than chosen by the user, so login can force a
-- rotation before the temporary credential sees any further use.
ALTER TABLE users ADD COLUMN must_change_password boolean NOT NULL DEFAULT false;
